// names.js

const stocks = [
    { symbol: "ANIM3", name: "Animation Corp" },
    { symbol: "COGN3", name: "Cognitive Ltd" },
    { symbol: "SEER3", name: "Seer Incorporated" },
    { symbol: "YDUQ3", name: "Education Group" },
    { symbol: "B3SA3", name: "Brazil SA" },
    { symbol: "BBAS3", name: "Brazilian Bank" },
    { symbol: "BBDCP1!", name: "BBD Corp" },
    { symbol: "BRAP4", name: "Brazilian Mining" },
    { symbol: "BRSR3", name: "Brazilian Resources" },
    { symbol: "CIEL3", name: "Consumer Emporium" },
    { symbol: "ITUB4", name: "Itau Corporation" },
    { symbol: "ITSA4", name: "Itausa Group" },
    { symbol: "SANB11", name: "Sanbank" },
    { symbol: "BPAC11", name: "Banco Pacific" },
    { symbol: "HAPV3", name: "Health & Pharma" },
    { symbol: "ODPV3", name: "Odyssey Pharma" },
    { symbol: "QUAL3", name: "Quality Pharmaceuticals" },
    { symbol: "FLRY3", name: "Flory Industries" },
    { symbol: "PGMN3", name: "Progemin Corp" },
    { symbol: "AALR3", name: "Advanced Labs" },
    { symbol: "HYPE3", name: "Hypnosis Pharma" },
    { symbol: "RADL3", name: "Radar Laboratories" },
    { symbol: "ABEV3", name: "Brazilian Brewery" },
    { symbol: "BEEF3", name: "Beef & Co" },
    { symbol: "BRFS3", name: "Brazilian Foods" },
    { symbol: "CRFB3", name: "Cerebral Foods" },
    { symbol: "JBSS3", name: "Juicy Burgers" },
    { symbol: "MEAL3", name: "Meals SA" },
    { symbol: "MDIA3", name: "Media Industries" },
    { symbol: "MRFG3", name: "Marfrig Group" },
    { symbol: "PCAR3", name: "Petrochemicals SA" },
    { symbol: "OIBR3", name: "Oi Communications" },
    { symbol: "TIMS3", name: "Tim Telecom" },
    { symbol: "VIVT3", name: "Vivo Telecommunications" },
    { symbol: "AMER3", name: "American Retailers" },
    { symbol: "PETZ3", name: "Petz Retail" },
    { symbol: "CEAB3", name: "Creative Apparel" },
    { symbol: "CVCB3", name: "CVC Brazil" },
    { symbol: "KLBN4", name: "Klabin SA" },
    { symbol: "PETR4", name: "Petrobras" },
    { symbol: "SUZB3", name: "Suzano SA" },
    { symbol: "ARZZ3", name: "Arzato Apparel" },
    { symbol: "GUAR3", name: "Guarani SA" },
    { symbol: "LREN3", name: "La Renzo" },
    { symbol: "ALPA4", name: "Alpaca Clothing" },
    { symbol: "VIVA3", name: "Viva Fashion" },
    { symbol: "VULC3", name: "Vulcan Co" },
    { symbol: "GRND3", name: "Grand Retail" },
    { symbol: "CMIG4", name: "Cemig SA" },
    { symbol: "CPLE3", name: "CPFL Energia" },
    { symbol: "ELET6", name: "Eletrobras" },
    { symbol: "ENGI11", name: "Engie SA" },
    { symbol: "EQTL3", name: "Equatorial Energy" },
    { symbol: "LIGT3", name: "Light SA" },
    { symbol: "CSAN3", name: "Cosan SA" },
    { symbol: "UGPA3", name: "Ultrapar" },
    { symbol: "IGTI11", name: "IGTech Inc" },
    { symbol: "JHSF3", name: "JHSF SA" },
    { symbol: "MULT3", name: "Multiplan SA" },
    { symbol: "BRPROD", name: "Brazilian Properties" },
    { symbol: "CYRE3", name: "Cyrela Brazil" },
    { symbol: "EVEN3", name: "Even SA" },
    { symbol: "GFSA3", name: "Gafisa SA" },
    { symbol: "MRVE3", name: "MRV Engineering" },
    { symbol: "TCSA3", name: "Technisa SA" },
    { symbol: "JHSF3", name: "JHSF SA" },
    { symbol: "EZTC3", name: "EZTec Empreendimentos" },
    { symbol: "TEND3", name: "Tenda SA" },
    { symbol: "HBOR3", name: "Hibor SA" },
    { symbol: "BBSE3", name: "BB Seguridade" },
    { symbol: "IRBR3", name: "IRB Brasil" },
    { symbol: "PSSA3", name: "Porto Seguro SA" },
    { symbol: "CSMG3", name: "Copasa MG" },
    { symbol: "SAPR11", name: "Sanepar" },
    { symbol: "SBSP3", name: "Sabesp" },
    { symbol: "CCRO3", name: "CCR SA" },
    { symbol: "ECOR3", name: "Ecorodovias" },
    { symbol: "EMBR3", name: "Embraer SA" },
    { symbol: "POMO4", name: "Pomona SA" },
    { symbol: "RAIL3", name: "Randon SA" },
    { symbol: "RAPT4", name: "Randon SA" },
    { symbol: "AZUL4", name: "Azul SA" },
    { symbol: "GOLL4", name: "Gol Linhas Aereas" },
    { symbol: "MOVI3", name: "Movida Participações" },
    { symbol: "RENT3", name: "Localiza Rent a Car" }
];

export default stocks;
